# Generated by Django 4.2.13 on 2024-06-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactrequest',
            options={'verbose_name_plural': 'Contact Request'},
        ),
    ]
