# Generated by Django 4.2.13 on 2024-06-05 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_request', '0003_contactrequest_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactrequest',
            options={},
        ),
    ]
