# Generated by Django 4.2.13 on 2024-06-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_request', '0005_alter_contactrequest_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
