# Generated by Django 4.2.13 on 2024-06-12 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groomers', '0002_groomers_updated_on'),
        ('home', '0003_about_image_services_service_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                 serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[
                    ('scheduled', 'Scheduled'), ('completed', 'Completed'),
                    ('cancelled', 'Cancelled')],
                 default='scheduled', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groomer', models.ForeignKey
                 (on_delete=django.db.models.deletion.CASCADE,
                  to='groomers.groomers')),
                ('service', models.ForeignKey
                 (on_delete=django.db.models.deletion.CASCADE,
                  to='home.services')),
                ('user', models.ForeignKey
                 (on_delete=django.db.models.deletion.CASCADE,
                  to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
