# Generated by Django 4.2.13 on 2024-06-27 08:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_about_image_services_service_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['position'], 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='services',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
