# Generated by Django 4.2.13 on 2024-06-05 12:27

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groomers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('groomer_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Groomers',
            },
        ),
    ]
