# Generated by Django 4.2.13 on 2024-06-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groomers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groomers',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
