# Generated by Django 4.2.13 on 2024-06-23 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groomers', '0003_groomerschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groomerschedule',
            name='lunch_end',
        ),
        migrations.RemoveField(
            model_name='groomerschedule',
            name='lunch_start',
        ),
    ]
